export { default as About } from './About';
export { default as LogIn } from './LogIn';
export { default as Products} from './Products';
export { default as Register } from './Register';
export { default as SingleProduct } from './SingleProduct';
export { default as Error } from './Error';
export { default as Orders } from './Orders';
export { default as CheckOut } from './CheckOut';
export { default as HomeLayout } from './HomeLayout';
export { default as Cart } from './Cart';
export { default as Landing } from './Landing';